### ISSUE TITLE
super.init need to be declared 

### ISSUE THREAD

**Issue by genthalili** [balvi/cuba-component-declarative-controllers#4]
`super.init()` need to be delcared in your `AnnotatableAbstractLookup`or `AnnotatableAbstractEditor<E>`

because if you declare your init in your Browser then it will never call it, which is quite annoying, spent some time until I found the issue.
Maybe it should be mentioned somewhere in the README.md

**Comment by bresche** [comment]
Hi, genthalili. Feel free to create a pull request.
