### ISSUE TITLE
[BUG] - corrupt binary of 0.6.0

### ISSUE THREAD

**Issue by mariodavid** [balvi/cuba-component-declarative-controllers#9]
hi @alferink @bresche @jhbaumgarten ,

there seems to be a bug in the 0.6.0 version. Some jar file is corrupt (https://bintray.com/balvi/cuba-components/download_file?file_path=de%2Fbalvi%2Fcuba%2Fdeclarativecontrollers%2Fdeclarativecontrollers-web%2F0.6.0%2Fdeclarativecontrollers-web-0.6.0-sources.jar).

Unfortunately it breaks https://github.com/mariodavid/cuba-component-data-import in 0.5.0 since I thought it would be a studio problem and did not pay proper attention.

It seems you did not correct uploaded the binary when releasing the version.

The CUBA people investigated and mentioned that it has nothing to do with studio itself:
https://www.cuba-platform.com/discuss/t/studio-throws-java-util-zipexception/5479/3

It might have something to do that you use the old way of uploading to bintray via an old approach. For the new way of doing it look here for examples: 
* https://www.cuba-platform.com/discuss/t/recommendations-on-developing-add-ons/4715
* https://github.com/mariodavid/cuba-component-data-import/blob/master/build.gradle#L61

Could you remove the old 0.6.0 version from bintray and release a proper one?

That would be great. There are already some complaints like this:
* https://www.cuba-platform.com/discuss/t/resource-exception-for-app-component/5504

Bye
Mario

**Comment by bresche** [comment]
Hey, Mario,

thank you for your message. I fixed the project. 

Regards Matthias
